Adding configs and packages so Sentry can catch frontend errors
uktrade/dit-contact-forms pull request #95
Opened 2021-06-15 14:50 UTC by Santino-Trade

2021-06-18 10:24 UTC, Santino-Trade commented on assets/javascript/global.js
> +module.exports = {
Need to remove this bit actually, its leftover from earlier

2021-06-18 10:48 UTC, kevincarrogan requested changes

2021-06-18 10:48 UTC, kevincarrogan commented on assets/javascript/global.js
> +});
I've been thinking we might want to run this even earlier (it's possible that some of the includes above could cause errors).

I think the best way to handle this is to have a separate entrypoint:
https://github.com/uktrade/dit-contact-forms/blob/aabe67cb0831f329559ce476d62e576fe0e0721e/webpack.config.js#L7:L15
that just does the Sentry import and init.

Then that script should be included in the head of all pages i.e. add it to the head in `base.html`.

2021-06-21 13:03 UTC, Santino-Trade commented on assets/javascript/global.js
> +});
I've added a new JS file and an entry point, the bundle made in the webpack config is already loaded up on base.html, so that was all that was needed. Tested it out locally, adding a broken constr at the top of global.js did trigger a report in Sentry.

2021-06-22 08:57 UTC, Santino-Trade commented on assets/javascript/global.js
> +});
Need another look at this, testing the helpdesk version, it might be that just adding the entry point puts the sentry trigger on the global page, but it isn't included on subpages (in this case, the cookie policy)

2021-06-24 09:06 UTC, kevincarrogan approved these changes

2021-06-24 10:21 UTC, merged